---
title: "Practical8"
output: html_notebook
---

*libraries*
```{r}
#install.packages("downloader")
library(tidyverse)
library(downloader)
library(rgdal)
library(sf)
library(ggplot2)
library(reshape2)
library(plotly)
library(highcharter)
library(ggthemes)
```

Get data
```{r}
LondonWards <- readOGR("/Volumes/ucfnnap/CASA_GIS and Sc/wk8/NewLondonWard/NewLondonWard.shp", layer="NewLondonWard")
LondonWardsSF <- st_as_sf(LondonWards)
extradata <- read_csv("https://www.dropbox.com/s/qay9q1jwpffxcqj/LondonAdditionalDataFixed.csv?raw=1")
```

Merge datasets
```{r}
LondonWardsSF <- merge(LondonWardsSF, extradata, by.x = "WD11CD", by.y = "Wardcode")
```

```{r}
summary(LondonWardsSF)
names(LondonWardsSF)
```

London data store for data key=value reference
https://londondatastore-upload.s3.amazonaws.com/instant-atlas/borough-profiles/atlas.html  

Simple histogram
```{r}
### style
th <- theme_tufte(base_family = "Georgia")

### AvgPubTrans = Average Public Transport Accesibility score, 2014
ggplot(LondonWardsSF, aes(AvgPubTran)) +
  geom_histogram() + th
```

Simple histogram binwidth = 0.1
```{r}
ggplot(LondonWardsSF, aes(AvgPubTran)) +
  geom_histogram(binwidth = 0.1) + th
```

Histogram with vertical lines Central Tendency
```{r}
CT <- ggplot(LondonWardsSF, aes(AvgPubTran)) +
  geom_histogram(binwidth = 0.1) + th +
  geom_vline(aes(xintercept = mean(AvgPubTran)), colour="yellow") +
  geom_vline(aes(xintercept = median(AvgPubTran)), colour="magenta") 
```

Calulate Mode
```{r}
### Rounded PTAL to get 'most typical' value (otherwise all are unique values)
x <- round(LondonWardsSF$AvgPubTran, digits = 1)
y <- table(x)
names(y)[which(y==max(y))]
```

Histogram with Mode
```{r}
CT + geom_vline(aes(xintercept = 2.4), colour="cyan")
```

Annotate Histogram
```{r}
m_ean <- annotate("text", label = paste("Mean\n", round(mean(LondonWardsSF$AvgPubTran), digits = 2)), x = mean(LondonWardsSF$AvgPubTran), y = 7, color = "white", size = 3, family = "Georgia", hjust =-.01)
m_edian <- annotate("text", label = paste("Median\n", round(median(LondonWardsSF$AvgPubTran), digits = 2)), x = median(LondonWardsSF$AvgPubTran), y = 3, color = "white", size = 3, family = "Georgia", hjust =-.01)
m_ode <- annotate("text", label = paste("Mode: ", 2.4), x = 2.4, y = 3, color = "white", size = 3, family = "Georgia", angle = 90, vjust =-.5)

CT + geom_vline(aes(xintercept = 2.4), colour="cyan") + m_ean + m_edian + m_ode
```

Kernel density smoothed frequency gradients
```{r}
ggplot(LondonWardsSF, aes(x=AvgPubTran, y=..density..)) + 
  geom_density(colour="red", fill="red", alpha=0.2) + 
  geom_density(colour="orange", fill="orange", alpha=0.2, adjust = 1/5) + 
  geom_density(colour="purple", fill="purple", alpha=0.2, adjust = 1/3) + th
```

Different Kernels
```{r}
ggplot(LondonWardsSF, aes(x=AvgPubTran, y=..density..)) + 
  geom_density(colour="red", fill="red", alpha=0.2, adjust = 1/3, kernel="gaussian") + 
  geom_density(colour="orange", fill="orange", alpha=0.2, adjust = 1/3, kernel="rectangular") + 
  geom_density(colour="purple", fill="purple", alpha=0.2, adjust = 1/3, kernel="cosine") + th
```





